<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1): ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher"
    id="switcher-language<?= $escaper->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $escaper->escapeHtml(__('Language')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-language-trigger<?= $escaper->escapeHtmlAttr($id) ?>"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-<?= $escaper->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <span><?= $escaper->escapeHtml($block->getStoreName()) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($block->getStores() as $_lang): ?>
                    <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                        <?php $targetUrl = $block->getViewModel()->getTargetStoreRedirectUrl($_lang); ?>
                        <?php $redirectUrl = $escaper->escapeUrl($targetUrl); ?>
                        <li class="view-<?= $escaper->escapeHtml($_lang->getCode()) ?> switcher-option">
                            <a
                            href="<?= /* @noEscape */ $redirectUrl ?>">
                                <?= $escaper->escapeHtml($_lang->getName()) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
