<?php $_filters = $block->getActiveFilters() ?>
<?php if (empty($_filters)) {
    return;
} ?>
<div class="filter-current" data-mage-init='{"collapsible":{"openedState":"active","collapsible":true,"active":true}}'>
    <strong class="block-subtitle filter-current-subtitle widget-title"
            role="heading"
            aria-level="2"
            data-role="title"
            data-count="<?= count($_filters); ?>">
        <?= /* @noEscape */ __('Now Shopping by') ?></strong>
    <ol class="items">
        <?php foreach ($_filters as $_filter): ?>
            <li class="item">
                <span class="filter-label" attribute-code="<?= $block->escapeHtmlAttr($_filter->getFilter()->getRequestVar()) ?>">
                    <?= $block->escapeHtml(__($_filter->getName())); ?>
                </span>
                <span class="filter-value" option-id='<?= $block->escapeHtmlAttr(is_array($_filter->getValue()) ? json_encode($_filter->getValue()) : $_filter->getValue()) ?>'>
                    <?= /* @noEscape */ $block->stripTags($_filter->getLabel()) ?>
                </span>
                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtml(__($_filter->getName())) . ' ' . $block->stripTags($_filter->getLabel());
                ?>
                <?php if ($clearLinkUrl): ?>
                    <a class="action previous" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Previous')) ?>">
                        <span><?= /* @noEscape */ __('Previous') ?></span>
                    </a>
                    <a class="action remove"
                       title="<?= $block->escapeHtmlAttr($_filter->getFilter()->getClearLinkText()) ?>"
                       href="<?= $block->escapeUrl($clearLinkUrl) ?>">
                        <span><?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                    </a>
                <?php else: ?>
                    <?php $removeUrl = $_filter->getRemoveUrl(); ?>
                    <a class="action remove" href="<?= $block->escapeUrl($removeUrl) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Remove')) . ' ' . $currentFilterName; ?>">
                        <span><i class="fa fa-times" aria-hidden="true"></i></span>
                    </a>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ol>
</div>
