<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $block->getSearchHelperViewModel()->getSearchHelper();
?>
<div class="block block-search">
    <div class="block block-title"><strong><?= $escaper->escapeHtml(__('Search')) ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form"
        action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </label>
                <div class="control">
                    <div class="control-wrapper">
                        <input id="search"
                               data-mage-init='{"quickSearch":{
                                    "formSelector":"#search_mini_form",
                                    "url":"<?= $escaper->escapeUrl($helper->getSuggestUrl())?>",
                                    "destinationSelector":"#search_autocomplete",
                                    "minSearchLength":"<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"}
                               }'
                               type="text"
                               name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                               value="<?= $escaper->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
                               placeholder="<?= $escaper->escapeHtmlAttr(__('Search...')) ?>"
                               class="input-text"
                               maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"
                               aria-expanded="false"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?= $block->getChildHtml() ?>
                    </div>
                    <i class="fas fa-times btn-close-search"></i>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                    title="<?= $escaper->escapeHtmlAttr(__('Search')) ?>"
                    class="action search"
                    aria-label="Search"
                >
                    <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
