<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Checkout\Block\Cart\Grid;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Grid $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
$hyvaCsp = $viewModels->require(HyvaCsp::class);
?>

<div x-data="initClearShoppingCartModal">
    <dialog
        role="alertdialog"
        x-show="isOpen"
        x-transition
        x-htmldialog="close"
        aria-labelledby="clearShoppingCartModal"
        class="p-6 bg-white shadow-xl rounded-md max-w-lg w-full z-50 backdrop:bg-black/50"
    >
        <p id="clearShoppingCartModal" class="text-xl mb-4 text-center">
            <strong><?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?></strong>
        </p>
        <p class="text-gray-700 text-center mb-6"><?= $escaper->escapeHtml(__('Are you sure you want to remove all items from your shopping cart?')) ?></p>
        <div class="actions-toolbar flex justify-center gap-4">
            <button type="button" class="btn action clear cursor-pointer transition-all duration-300 ease-in-out bg-[#dda245] hover:bg-[#c99538] hover:shadow-md border-0 text-white font-semibold py-2 px-6 shadow-none" @click="close"><?= $escaper->escapeHtml(__('Cancel')) ?></button>
            <button type="button" class="btn action clear cursor-pointer transition-all duration-300 ease-in-out bg-[#dda245] hover:bg-[#c99538] hover:shadow-md border-0 text-white font-semibold py-2 px-6 shadow-none" @click="clearCart"><?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?></button>
        </div>
    </dialog>

    <button
        id="empty_cart_button"
        type="button"
        class="btn action clear cursor-pointer transition-all duration-300 ease-in-out bg-[#dda245] hover:bg-[#c99538] hover:shadow-md border-0 text-white font-semibold py-3 px-6 shadow-none"
        @click="open"
    ><?= $escaper->escapeHtml(__('Clear Shopping Cart')) ?></button>
</div>
<script>
    function initClearShoppingCartModal() {
        return {
            isOpen: false,
            open() {
                this.isOpen = true;
            },
            close() {
                this.isOpen = false;
            },
            clearCart() {
                hyva.postForm({
                    action: '<?= $escaper->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>',
                    data: { update_cart_action: 'empty_cart' }
                });
            }
        };
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('initClearShoppingCartModal', initClearShoppingCartModal)
    }, { once: true })
</script>
<?php $hyvaCsp->registerInlineScript() ?>
