<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

// phpcs:disable Generic.WhiteSpace.ScopeIndent
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductStockItem;
use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;

/** @var Renderer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductStockItem $stockItemViewModel */
$stockItemViewModel = $viewModels->require(ProductStockItem::class);

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

$minSalesQty = $stockItemViewModel->getMinSaleQty($product);
$maxSalesQty = $stockItemViewModel->getMaxSaleQty($product);
$qty = $stockItemViewModel->isQtyDecimal($product)
    ? $block->getQty()
    : (int) $block->getQty();

$step = $stockItemViewModel->getQtyIncrements($product)
    ? $stockItemViewModel->getQtyIncrements($product)
    : null;

/**
 * sets minimum and maximum values taking into account the values set in the admin,
 * but taking into account the value of Qty Increments
 */
if ($step) {
    $minSalesQty = ceil($minSalesQty / $step) * $step;
    $maxSalesQty = floor($maxSalesQty / $step) * $step;
    $qty = ceil($qty / $step) * $step;
}

$maxSalesQtyLength = ($maxSalesQty ? strlen((string) $maxSalesQty) : 4)
    + (/* add one if decimal for separator */ (int) $stockItemViewModel->isQtyDecimal($product));

?>
<article class="cart item flex flex-col md:flex-row gap-4 md:gap-0 items-center w-full"
    <?php foreach ($block->getData('cart_item_data_attributes') ?? [] as $attribute => $include): ?>
        <?php if ($include): ?>
            <?php /** Append data-* attributes based on layout XML arguments */ ?>
            <?= $escaper->escapeHtml(sprintf('data-%s', $attribute)); ?>="<?= $escaper->escapeHtmlAttr($item->getData($attribute)); ?>"
        <?php endif; ?>
    <?php endforeach; ?>
>
    <!-- Item Column -->
    <div class="flex flex-col md:flex-row gap-4 items-center w-full md:w-2/5 md:pl-4">
        <?php if ($block->hasProductUrl()): ?>
            <a
                href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
                tabindex="-1"
                class="product-item-photo shrink-0 w-24 md:w-auto"
            >
        <?php else: ?>
            <div class="product-item-photo shrink-0 w-24 md:w-auto">
        <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')
                ->setTemplate('Magento_Catalog::product/image.phtml')
                ->toHtml() ?>
        <?php if ($block->hasProductUrl()): ?>
            </a>
        <?php else: ?>
            </div>
        <?php endif; ?>

        <div class="product-item-details grow text-center md:text-left">
            <h3 class="product-item-name text-[15px] font-semibold break-all">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>" class="text-gray-900 hover:text-gray-600 transition-colors capitalize tracking-wide">
                        <?= $escaper->escapeHtml($block->getProductName()) ?>
                    </a>
                <?php else: ?>
                    <span class="text-gray-900 capitalize tracking-wide"><?= $escaper->escapeHtml($block->getProductName()) ?></span>
                <?php endif; ?>
            </h3>

            <?php if ($options = $block->getOptionList()): ?>
                <dl class="mt-2 item-options table text-sm mx-auto md:mx-0">
                    <?php foreach ($options as $option): ?>
                        <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <div class="table-row">
                            <dt class="table-cell font-normal min-w-16 pe-2 pb-1 text-fg-secondary">
                                <?= $escaper->escapeHtml($option['label']) ?>
                            </dt>
                            <dd class="table-cell font-bold pb-1">
                                <?php if (isset($formatedOptionValue['full_view'])): ?>
                                    <?= $escaper->escapeHtml($formatedOptionValue['full_view']) ?>
                                <?php else: ?>
                                    <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        </div>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>

            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class="cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?> mt-2">
                        <div><?= $escaper->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($item)->toHtml() ?>
            <?php endif;?>
        </div>
    </div>

    <!-- Price Column -->
    <div class="w-full md:w-1/5 flex justify-center text-center">
        <span class="text-gray-500 font-medium md:text-lg">
            <span class="md:hidden mr-2"><?= $escaper->escapeHtml(__('Price:')) ?></span>
            <?= $block->getUnitPriceHtml($item) ?>
        </span>
    </div>

    <!-- Qty Column -->
    <div class="w-full md:w-1/5 flex justify-center text-center">
        <label class="control qty my-0 w-20">
            <span class="sr-only"><?= $escaper->escapeHtml(__('Qty')) ?></span>
            <input
                name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]"
                value="<?= $escaper->escapeHtmlAttr($qty) ?>"
                title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                class="form-input qty text-center w-full !rounded-none !border-gray-200"
                required
                <?php if ($stockItemViewModel->isQtyDecimal($product)): ?>
                type="text"
                pattern="[0-9]+(\.[0-9]{1,<?= /** @noEscape */ $maxSalesQtyLength ?>})?"
                inputmode="decimal"
                <?php else: ?>
                type="number"
                pattern="[0-9]{0,<?= /** @noEscape */ $maxSalesQtyLength ?>}"
                inputmode="numeric"
                <?php if ($minSalesQty): ?>min="<?= /** @noEscape */ $minSalesQty ?>"<?php endif; ?>
                <?php if ($maxSalesQty): ?>max="<?= /** @noEscape */ $maxSalesQty ?>"<?php endif; ?>
                <?php if ($step): ?>step="<?= /** @noEscape */ $step ?>"<?php endif; ?>
                <?php endif; ?>
                data-role="cart-item-qty"
            >
        </label>
    </div>

    <!-- Subtotal Column -->
    <div class="w-full md:w-1/5 flex flex-col items-center md:items-end justify-center md:pr-4">
        <div class="font-bold text-[18px] text-gray-500">
            <span class="md:hidden mr-2"><?= $escaper->escapeHtml(__('Subtotal:')) ?></span>
            <?= $block->getRowTotalHtml($item) ?>
        </div>
        <div class="item-actions mt-3 flex flex-wrap items-center justify-end gap-3 text-gray-600 [&_a]:text-gray-600 [&_a:hover]:text-primary [&_button]:text-gray-600 [&_button:hover]:text-primary [&_button]:cursor-pointer [&_a]:cursor-pointer [&_button]:transition-colors [&_a]:transition-colors">
            <?= /* @noEscape */ $block->getActions($item) ?>
        </div>
    </div>
</article>
