<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */
?>
<div class="toolbar-sorter sorter flex items-center order-1 justify-end">
    <label class="inline-block">
        <select data-role="sorter"
                name="sorter"
                class="form-select sorter-options h-10 border border-[#ececec] px-3 py-1 font-semibold text-xs tracking-wider uppercase focus:outline-none"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Sort By')) ?>"
                @change="changeUrl(
                    'product_list_order',
                    $event.currentTarget.options[$event.currentTarget.selectedIndex].value,
                    options.orderDefault
                )">
            <?php foreach ($block->getAvailableOrders() as $orderCode => $orderLabel):?>
                <option value="<?= $escaper->escapeHtmlAttr($orderCode) ?>"
                    <?php if ($block->isOrderCurrent($orderCode)): ?>
                        selected="selected"
                    <?php endif; ?>
                    >
                    <?= $escaper->escapeHtml(__($orderLabel)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </label>
</div>
