<?php /** $block Forever\Core\Block\ZoomInOut */ ?>
<?php if ($block->getConfigData()): ?>
    <div class="zoom-in-out-button">
        <a href="javascript:void(0)" class="zoom-in" ><?= /* @noEscape*/ __('Zoom In') ?></a>
        <a href="javascript:void(0)" class="zoom-out" style="display: none"><?= /* @noEscape*/ __('Zoom Out') ?></a>
    </div>
<?php endif; ?>

<script>
require(['jquery','jquery/ui'], function ($) {
    $(document).ready(function(){
        $(function() {
            $(".page-products .products.wrapper").addClass("zoom-out");
            $(".page-products .zoom-out").click(function(){
              if($(".page-products .products.wrapper").hasClass("zoom-in")) {
                $(".products.wrapper").removeClass("zoom-in");
                $(".products.wrapper").addClass("zoom-out");
              }
              $(".zoom-in").css("display", "block");
              $(".zoom-out").css("display", "none");
            });
            $(".page-products .zoom-in").click(function(){
              if($(".page-products .products.wrapper").hasClass("zoom-out")) {
                $(".products.wrapper").removeClass("zoom-out");
                $(".products.wrapper").addClass("zoom-in");
              }
              $(".zoom-out").css("display", "block");
              $(".zoom-in").css("display", "none");
            });
        })
    });
});
</script>