<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <div class="empty-cart-img">
        <img src="<?= /* @noEscape */ $block->getViewFileUrl('Magento_Checkout/images/empty-cart.png'); ?>"
        alt="empty-cart" width="169" height="145">
    </div>
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <p><?= $escaper->escapeHtml(__('You have no items in your shopping cart.')) ?></p>
    <p><?= $escaper->escapeHtml(
        __(
            'Click <a href="%1">here</a> to continue shopping.',
            $escaper->escapeUrl($block->getContinueShoppingUrl())
        ),
        ['a']
    ) ?>
    </p>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Checkout/js/empty-cart": {}
    }
}
</script>
