<div class="dailydeal-information">
    <span class="message info">
        <p><?= /* @noEscape */ __('If you are not able to see Dailydeals on Home page, Please check above scenarios') ?></p>
        <p><?= /* @noEscape */ __('1. You can add more time from the configuration and select further date from today.') ?></p>
        <p><?= /* @noEscape */ __('2. Check the Product is available with the SKU which you entered in the configuration.') ?></p>
    </span>
</div>
<style type="text/css">
span.message.info {
    width: 100%;
    display: block;
    left: 0;
    box-sizing: border-box;
}
body .message:before {
    top: 28px;
}
</style>