<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\BlockJsDependencies;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Catalog\Block\Product\Image;
use Magento\Framework\Escaper;

/** @var Image $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

$pageJsRegistry = $viewModels->require(BlockJsDependencies::class);
$pageJsRegistry->setBlockTemplateDependency($block, 'Magento_Catalog::product/list/js/image.phtml');

$customAttributes = $block->getCustomAttributes();
$hasLoadingAttribute = false;
$src = $block->getImageUrl();
if (is_array($customAttributes)) {
    $hasLoadingAttribute = $customAttributes['loading'] ?? false;
    if (isset($customAttributes['data-src'])) {
        $src = $customAttributes['data-src'];
        unset($customAttributes['data-src']);
    }
} elseif (is_string($customAttributes)) {
    $hasLoadingAttribute = strpos($customAttributes, 'loading=') !== false;
    if (preg_match('/data-src="([^"]+)"/', $customAttributes, $matches)) {
        $src = $matches[1];
        $customAttributes = preg_replace('/data-src="[^"]+"/', '', $customAttributes);
    }
}
?>
<img
    src="<?= $escaper->escapeUrl($src) ?>"
    width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
    height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
    alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
    class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
    <?php if (!$hasLoadingAttribute): ?>
        loading="lazy"
    <?php endif; ?>
    x-data="initProductItemImage"
    @update-gallery-<?= (int)$block->getProductId() ?>.window="updateImage"
    <?php if (is_string($customAttributes)): ?>
        <?= /* @noEscape */ $customAttributes ?>
    <?php elseif (is_array($customAttributes)): ?>
        <?php foreach ($customAttributes as $name => $value): ?>
            <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtmlAttr($value) ?>"
        <?php endforeach; ?>
    <?php endif; ?>
>
